const PDFDocument = require("pdfkit");

/**
 * Generates a PDF buffer from the structured summary.
 * @param {Object} summaryData { keyPoints, actionItems, decisions }
 * @returns {Promise<Buffer>}
 */
function generatePDF(summaryData) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];

      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));

      // Helper function to draw sections
      const addSection = (title, items) => {
        if (!items || items.length === 0) return;

        doc
          .font("Helvetica-Bold")
          .fontSize(16)
          .fillColor("#333333")
          .text(title, { underline: true });
        doc.moveDown(0.5);

        doc.font("Helvetica").fontSize(12).fillColor("#000000");
        items.forEach((item) => {
          doc.text(`• ${item.trim()}`);
          doc.moveDown(0.3);
        });

        doc.moveDown(1);
      };

      // ─── Header ─────────────────────────────────────────────────────────────
      doc
        .font("Helvetica-Bold")
        .fontSize(24)
        .fillColor("#4285F4") // Google Blue
        .text("Meeting Summary", { align: "center" });

      doc.moveDown(0.5);
      doc
        .font("Helvetica")
        .fontSize(10)
        .fillColor("#888888")
        .text(`Generated on: ${new Date().toLocaleString()}`, {
          align: "center",
        });
      doc.moveDown(2);

      // ─── Body ───────────────────────────────────────────────────────────────
      addSection("Key Points", summaryData.keyPoints);
      addSection("Action Items", summaryData.actionItems);
      addSection("Decisions", summaryData.decisions);

      // ─── Footer ─────────────────────────────────────────────────────────────
      doc.moveDown(2);
      doc
        .font("Helvetica-Oblique")
        .fontSize(10)
        .fillColor("#aaaaaa")
        .text("Generated by Google Meet Auto-Summarizer Extension", {
          align: "center",
        });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generatePDF };
